### ISSUE TITLE
Dependency checks fail with Invalid specifier: 'python_version'

### ISSUE THREAD

**Issue by medariox** [sharkykh/medusa_vendor_tools#1]
```
D:\Development\Medusa (develop -> origin)
λ python D:\Development\Medusa\vendor.py pint
Removing: [WindowsPath('D:/Development/Medusa/ext/pint')]
Package pint found in list, using that
Installing vendored library `pint` to `ext`
+++++ [ pip | py3 ] +++++
Collecting pint
  Downloading https://files.pythonhosted.org/packages/15/9d/bf177ebbc57d25e9e296addc14a1303d1e34d7964af5df428a8332349c42/Pint-0.9-py2.py3-none-any.whl (138kB)
     |████████████████████████████████| 143kB 1.3MB/s
Installing collected packages: pint
Successfully installed pint-0.9
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
----- [ pip | py3 ] -----
Installed: Pint==0.9 to ext
+++++++++++++++++++++
+ Dependency checks +
+-------------------+
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pkg_resources\_vendor\packaging\specifiers.py", line 601, in __init__
    parsed.add(Specifier(specifier))
  File "D:\Python36\lib\site-packages\pkg_resources\_vendor\packaging\specifiers.py", line 85, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
pkg_resources._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: 'python_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Development\Medusa\vendor.py", line 339, in <module>
    main(**args.__dict__)
  File "D:\Development\Medusa\vendor.py", line 122, in main
    spec = SpecifierSet(d['version'])
  File "D:\Python36\lib\site-packages\pkg_resources\_vendor\packaging\specifiers.py", line 603, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "D:\Python36\lib\site-packages\pkg_resources\_vendor\packaging\specifiers.py", line 85, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
pkg_resources._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: 'python_version'
```

```
Windows 10 1903 x64
Python 3.6.8
setuptools 40.6.3
pip 19.1
```

**Comment by sharkykh** [comment]
Oops, forgot to watch my own repository.
Thanks, will look into it 👍 
Worked well for other packages?

**Comment by medariox** [comment]
No issues with other packages 👌
